### ISSUE TITLE
assessment of whether "individuals.txt" is in the folder

### ISSUE THREAD

**Issue by eriqande** [bwringe/parallelnewhybrid#1]
If the Individuals.txt file is not in there, then `indiv.file.exists` has length 0 which throws an error when it gets used in:

``` r
if(indiv.file.exists > 0){
      path.indiv.file <- paste0(folder.data, files.anal[indiv.file.exists])
      files.anal <- files.anal[-indiv.file.exists]
    }
    if(indiv.file.exists == 0){
      writeLines("Note: An individual file has not been provided. Please refer to the help file for more information")
    }
```

I could fix this in my fork.  Haven't yet, just wanted to file the issue.

**Comment by bwringe** [comment]
Hi Eric,

I am not sure I understand the issue? This error message was hard coded
into the function to try and get users to include an individual file (an
example individual file is included in the package).

I can see that perhaps this may be a bit too stringent. So, an alternative
might be to prompt the user that there is no individual file, but then ask
them if they would like to continue with the analysis anyway.

The only issue I can see with this is that the function later looks for the
individual file to put into the NH.Results folders, so allowing the user to
not have an individual file may cause the function to then fail at the
point it tries to move a file that does not exist.

This would then require an if statement, that if the user doesn't have an
individual file, and still wants to proceed with the analysis, then the
function will not look to move an individual file.

The issue that arises then, is that if they are using the hybrid detective
package, then it will want an individual file for most of the functions it
contains.

So, I am not sure what the best solution to this is?

Brendan

**Comment by eriqande** [comment]
Hi Brendan!

Wow! quick reply!  I was still playing with parallelnewbrid and having a
great time with it.  Are you avalable for a skype?

**Comment by eriqande** [comment]
The problem I saw with it was that it failed with this error message:

"Error in if (indiv.file.exists > 0) { : argument is of length zero"

which isn't super intuitive.  I'll give a whack at a few things and send a
pull request.

eric

**Comment by bwringe** [comment]
Hi Eric,

I am free to Skype. I can see if the others are around as well.

BW
