### ISSUE TITLE
Cryptic errors with user input file

### ISSUE THREAD

**Issue by tkchafin** [bwringe/parallelnewhybrid#4]
When using my own input files (attached), I get a ton of errors/ wanrings, and I can't figure out the source of them. I can run the program using the example datasets just fine. 

> parallelnh_OSX(folder.data="./bal/", where.NH=my.NH, burnin=100, sweeps=100)

Errors: 
Eating the wrong fish number!!  Was expecting to find the number 1 at the begninning of this line of data, but found 0 instead. [In repetition, before "data initialization" and "seedfile" outputs]

WARNING: i=6 >= Num=6 in IntegerFromProbsRV().  Probably only a problem while initializing the chain.  i reset to 4
WARNING: i=6 >= Num=6 in IntegerFromProbsRV().  Probably only a problem while initializing the chain.  i reset to 0
WARNING: i=6 >= Num=6 in IntegerFromProbsRV().  Probably only a problem while initializing the chain.  i reset to 3
[In repetition during each sweep]

Any ideas? I thought maybe it was caused by missing data for a locus within 1 or more populations, so I edited my script creating the inputs to delete loci lacking data for any 1 group (Parent 1, Parent2, admix), but that didn't fix the problem.
[bal_individuals.txt](https://github.com/bwringe/parallelnewhybrid/files/1511464/bal_individuals.txt)
[bal.txt](https://github.com/bwringe/parallelnewhybrid/files/1511465/bal.txt)

**Comment by bwringe** [comment]
The "eating wrong fish number!" error is coming directly from NewHybrids, not parallelnewhybrid. It might have to do with the fact that you have your data coded as 0, 1, 2. NewHybrids uses 0 to represent missing data, and cannot handle a locus with one missing allele. So, when it sees "00" it ignores, but when it sees 10,  it reads only the 1, then skips ahead. This causes it to mix up the start end of the lines based on the defined number of loci to expect.

I would suggest recoding your allele calls.

As an aside, you seem to have a VERY large number of alleles. I would recommend reducing this number substantially as you will end up with problems of convergence of the MCMC chains, and also likely an over-estimation of your degree of certainty in regards to assigning individuals to classes. Refer to the discussion of linkage in the original NewHybrids paper. There are function available to do this, such as in my other package "hybriddetective" (sorry for the shameless plug).

Brendan

**Comment by tkchafin** [comment]
Thanks! I hadn't noticed that I had them coded 0,1,2. I'm converting from a Structure file, and had been changing "-9" (missing) to 0 as well, so had been interpreting all of the 0's in my output as missing values. 

I am working with RAD data and have already sampled 1 SNP per locus, but will also add random down-sampling to my file converting script to help with convergence issues. 

Will let you know if the re-coding fixes it.

**Comment by tkchafin** [comment]
Got it fixed! Thanks.
